apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-uuw8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-uuw8
    app.kubernetes.io/part-of: ci1t-830-0012-app
  name: devfile-sample-uuw8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-uuw8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-uuw8
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0012-tenant/ci1t-830-0012-app/devfile-sample-uuw8@sha256:235e26c775a3f3c339f0430c8e2a9321703747c2af9f0749b1046bbbef04bbde
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
